<<<<<<<< HEAD:lib/db/migrations/versions/9988463fe2c2_initialize_tables.py
"""initialize tables

Revision ID: 9988463fe2c2
Revises: 
Create Date: 2025-05-29 22:47:38.390252
========
"""Initial schema with 3 tables

Revision ID: c56777819eb9
Revises: 
Create Date: 2025-05-29 20:51:03.991294
>>>>>>>> 5ae788e (tables reinitialize):lib/db/migrations/versions/c56777819eb9_initial_schema_with_3_tables.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:lib/db/migrations/versions/9988463fe2c2_initialize_tables.py
revision: str = '9988463fe2c2'
========
revision: str = 'c56777819eb9'
>>>>>>>> 5ae788e (tables reinitialize):lib/db/migrations/versions/c56777819eb9_initial_schema_with_3_tables.py
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('medical_license_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medical_license_number'),
    sa.UniqueConstraint('national_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('inpatient', 'outpatient', 'discharged', name='statusenum'), nullable=False),
    sa.Column('current_medication', sa.String(), nullable=True),
    sa.Column('chronic_conditions', sa.String(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('app_status', sa.Enum('scheduled', 'checked_in', 'cancelled', 'completed', 'no_show', name='app_statusenum'), nullable=False),
    sa.Column('app_type', sa.Enum('consultation', 'follow_up', 'surgery', 'emergency', name='app_typeenum'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
